version: '3'
services:
  nishida-web:
    container_name: nishida-web
    build: .
    restart: always
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./html:/usr/local/apache2/htdocs
      - ./cgi-bin:/usr/local/apache2/cgi-bin
    environment:
      VIRTUAL_HOST: nishida.decimoll.0j0.jp
      LETSENCRYPT_HOST: nishida.decimoll.0j0.jp
      LETSENCRYPT_EMAIL: decimoll@d00.itscom.net
      TZ: "Asia/Tokyo"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
